/* Generated By:JavaCC: Do not edit this line. OperationParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OperationParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FOR = 1;
  /** RegularExpression Id. */
  int EQUAL = 2;
  /** RegularExpression Id. */
  int SEMICOLON = 3;
  /** RegularExpression Id. */
  int LEFT_PAREN = 4;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 5;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int OP = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"for\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<ID>",
    "<OP>",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
  };

}
